### ISSUE TITLE
Run test.py but BER is around 0.5

### ISSUE THREAD

**Issue by FelixFeiyu** [MahdiShAhmadi/ReDMark#17]
I directly download all files from the github and run the `test.py` without any modification. However  all the BERs,  are around 0.5, this isn't reasonal and same as the results in the paper. So what's the wrong? I am confused.

**Comment by Feiyu-Chan** [comment]
I checked again and found the model's weights cannot be written successfully, but there is no any error output

**Comment by Feiyu-Chan** [comment]
I believe the stored weights_final.h5 may be broken down. Because when I loaded the MT weights to the model, the original model and the loaded model have the same weight. And I try use other public weights like JT and GT, after loading, the weights are changed.

**Comment by MahdiShAhmadi** [comment]
Are you using Tensorflow==1.15.4?
Also your h5py should be compatible. 

A good debugging would be to print weight before and after loading from h5 file.

**Comment by h360hiro** [comment]
Hi, 
I'm looking for a solution to a problem I have with Tensorflow ==1.15.4. 
I can say from my running that the resulting values are indeed very different between Tensorflow==1.15.4 and e.g. ==1.15.0.
Since I am running on Anaconda3 virtual environment, I was running in the environment with ==1.15.0 instead of ==1.15.4 which is not present in the `conda search tensorflow`. Then I ran it again on Anaconda3 after typing `pip install tensorflow==1.15.4`, and PSNR and SSIM were greatly improved.
(PSNR and SSIM are still about 1 and 0.1 less than the paper's values...)
The versions of the main modules in my environment are as follows
tensorflow==1.15.4
opencv==3.4.2
(At least in my environment, opencv-python does not exist when I type `conda search opencv-python` and does not work correctly when installed with `pip install opencv-python` .)
scikit-learn==1.0.2
matplotlib==3.5.3
scikit-image==0.19.3
tqdm==4.64.1
h5py==2.8.0
numpy==1.18.5
keras-applications==1.0.8
keras-processing==1.1.2

I can't mention BER yet, but I hope it will be of help.
Thank you very much.

**Comment by FelixFeiyu** [comment]
> Are you using Tensorflow==1.15.4? Also your h5py should be compatible.
> 
> A good debugging would be to print weight before and after loading from h5 file.

I installed tensorflow==1.15.4 and h5py ==2.10.0. And I print the weights, I am sure, the weight before and after loading are different. But the BER are still around 0.5.

**Comment by h360hiro** [comment]
Sorry for the late.
Quite simply, I faced a similar situation.
First, for the MT-Net weighted tests on GitHub, the BER of Salt&Pepper noise all record 40~50%. Next is patterned-pixel-elimination, which has a large difference from the paper, recording a maximum of about 4%. For the other noises, there is almost no difference more than 1%.
Next, as for the test with the new_model created by Train.py on Github, the Salt&Pepper noise is almost non-functional as in the previous case. Also, the Median noise differs from the paper by up to 40%, and the JPEG, GaussianBlur, and Resizing noise differ by almost 20%.
Considering the above, at least for the Salt&Pepper noise, the current version of Train.py does not seem to be learning properly. Also, the current Train.py does not seem to be able to reproduce the MT-Net that are already available.　Either the code itself does not work well, or the environment is not suitable. What do you think, Mr. Mahdi? If you think it is the latter, I would like to see the details (version, etc.) of the environment you were running the program in.

**Comment by MahdiShAhmadi** [comment]
Sorry for the late response. As you mentioned, sometimes the package versions cause these kinds of issues. As the code was originally  made for tensorflow 1, we decided to upgraded it to tensorflow 2. This should resolve a lot of issues. Please let us know should there be any other problems.
